app/blueprints/config.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template

# from flask_login import current_user
from app.services import ConfigInfo, JobHandler

config_bp = Blueprint("config", __name__)


@config_bp.route("/", methods=["GET"])
def index():

    jobs = JobHandler.get_all()
    return render_template("config/index.html", jobs=jobs, config=ConfigInfo.get_all())


@config_bp.route("/about")
def about():
    return render_template("config/about.html")

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Welcome to Modern Flask!{% endblock %}</title>
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}" type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
</head>

<body>
    <main class="container">
        <header>
            <h1 class="text-center display-4">
                <a href="{{ url_for('config.index') }}" class="text-success"><strong>Modern Flask</strong></a>
                <small class="text-muted sub-title">to the world</small>
            </h1>
        </header>
        {% for message in get_flashed_messages() %}
        <div class="alert alert-info">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message }}
        </div>
        {% endfor %}
        {% block content %}{% endblock %}
        <footer class="text-center">
            {% block footer %}
            <p><a id="bottom" href="#" title="Go Top">&uarr;</a></p>
            {% endblock %}
        </footer>
    </main>

    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.2.1.slim.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
</body>

</html>